/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.0-42-g8fd2dc3f2b-20220331"
#endif /* AVUTIL_FFVERSION_H */
